<template>
  <svg
    version="1.1"
    id="Layer_1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px"
    y="0px"
    width="24px"
    height="24px"
    viewBox="0 0 24 24"
    enable-background="new 0 0 24 24"
    xml:space="preserve"
  >
    <image
      id="image0"
      width="24"
      height="24"
      x="0"
      y="0"
      href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAQAAABKfvVzAAAABGdBTUEAALGPC/xhBQAAACBjSFJN
AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAJcEhZ
cwAACxMAAAsTAQCanBgAAAAHdElNRQfnAQwOIhbp28npAAAAtUlEQVQ4y9WRsQ3CMBBFX4IFzACk
zgw0bMAQTAB7sIiJItEhKGAIRAkVLUSKOygwhU0kB6RLh/J/dbr/pPM3tEIJOQbDmrRZ/I71Lkhk
IK/iFksmAyYAyvo6FnArA/tg2sknpRTVQTdGzXrKKClZNYv/XZ1gipkwY8qBF6BYMgau3+UC9Flw
8e1oFArtpzNzevX4kFPww7qKOx8ZhMA2WP/yxgUjDzzoCq99urM+gEVW5Hppv94QoVeTogEWCgAA
ACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0wMS0xMlQxMzozNDoyMiswMTowMD/KnzgAAAAldEVYdGRh
dGU6bW9kaWZ5ADIwMjMtMDEtMTJUMTM6MzQ6MjIrMDE6MDBOlyeEAAAAAElFTkSuQmCC"
    />
  </svg>
</template>
